package com.github.mdjdrn1.MPKKrakowTimetable.serializer;

import com.github.mdjdrn1.MPKKrakowTimetable.lines.*;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.AssertionsForInterfaceTypes.assertThat;

public class XmlSerializerTest
{
    @Test
    void is501XmlValid() throws ParsingException, ConnectionError
    {
        String expected = "<line>\n" +
                "  <number>501</number>\n" +
                "  <course>\n" +
                "    <course>\n" +
                "      <direction>Chełmońskiego Pętla</direction>\n" +
                "      <timetable>\n" +
                "        <timetable>\n" +
                "          <description>Weekday</description>\n" +
                "          <hours>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list>\n" +
                "              <string>45</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>05</string>\n" +
                "              <string>25</string>\n" +
                "              <string>40</string>\n" +
                "              <string>55</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>11</string>\n" +
                "              <string>28</string>\n" +
                "              <string>43</string>\n" +
                "              <string>57</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>11</string>\n" +
                "              <string>26</string>\n" +
                "              <string>41</string>\n" +
                "              <string>56</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>11</string>\n" +
                "              <string>26</string>\n" +
                "              <string>41</string>\n" +
                "              <string>56</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>11</string>\n" +
                "              <string>26</string>\n" +
                "              <string>39</string>\n" +
                "              <string>52</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>07</string>\n" +
                "              <string>22</string>\n" +
                "              <string>37</string>\n" +
                "              <string>52</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>07</string>\n" +
                "              <string>22</string>\n" +
                "              <string>37</string>\n" +
                "              <string>52</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>07</string>\n" +
                "              <string>23</string>\n" +
                "              <string>38</string>\n" +
                "              <string>53</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>08</string>\n" +
                "              <string>23</string>\n" +
                "              <string>37</string>\n" +
                "              <string>52</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>07</string>\n" +
                "              <string>22</string>\n" +
                "              <string>37</string>\n" +
                "              <string>52</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>07</string>\n" +
                "              <string>22</string>\n" +
                "              <string>37</string>\n" +
                "              <string>52</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>07</string>\n" +
                "              <string>22</string>\n" +
                "              <string>37</string>\n" +
                "              <string>52</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>07</string>\n" +
                "              <string>22</string>\n" +
                "              <string>37</string>\n" +
                "              <string>52</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>12</string>\n" +
                "              <string>29</string>\n" +
                "              <string>44</string>\n" +
                "              <string>59</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>14</string>\n" +
                "              <string>30</string>\n" +
                "              <string>45</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>02</string>\n" +
                "              <string>17</string>\n" +
                "              <string>37</string>\n" +
                "              <string>57</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>16</string>\n" +
                "              <string>33</string>\n" +
                "              <string>53</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>13</string>\n" +
                "              <string>33</string>\n" +
                "            </list>\n" +
                "            <list/>\n" +
                "          </hours>\n" +
                "        </timetable>\n" +
                "        <timetable>\n" +
                "          <description>Saturdays</description>\n" +
                "          <hours>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list>\n" +
                "              <string>10</string>\n" +
                "              <string>40</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>10</string>\n" +
                "              <string>40</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>08</string>\n" +
                "              <string>38</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>06</string>\n" +
                "              <string>26</string>\n" +
                "              <string>46</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>06</string>\n" +
                "              <string>26</string>\n" +
                "              <string>46</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>06</string>\n" +
                "              <string>26</string>\n" +
                "              <string>46</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>06</string>\n" +
                "              <string>26</string>\n" +
                "              <string>46</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>06</string>\n" +
                "              <string>26</string>\n" +
                "              <string>46</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>06</string>\n" +
                "              <string>26</string>\n" +
                "              <string>46</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>06</string>\n" +
                "              <string>26</string>\n" +
                "              <string>46</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>06</string>\n" +
                "              <string>26</string>\n" +
                "              <string>46</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>06</string>\n" +
                "              <string>26</string>\n" +
                "              <string>46</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>06</string>\n" +
                "              <string>26</string>\n" +
                "              <string>46</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>06</string>\n" +
                "              <string>26</string>\n" +
                "              <string>47</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>07</string>\n" +
                "              <string>27</string>\n" +
                "              <string>48</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>09</string>\n" +
                "              <string>33</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>04</string>\n" +
                "              <string>33</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>03</string>\n" +
                "              <string>33</string>\n" +
                "            </list>\n" +
                "            <list/>\n" +
                "          </hours>\n" +
                "        </timetable>\n" +
                "        <timetable>\n" +
                "          <description>Holidays</description>\n" +
                "          <hours>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list>\n" +
                "              <string>10</string>\n" +
                "              <string>40</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>10</string>\n" +
                "              <string>40</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>08</string>\n" +
                "              <string>38</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>06</string>\n" +
                "              <string>26</string>\n" +
                "              <string>46</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>06</string>\n" +
                "              <string>26</string>\n" +
                "              <string>46</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>06</string>\n" +
                "              <string>26</string>\n" +
                "              <string>46</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>06</string>\n" +
                "              <string>26</string>\n" +
                "              <string>46</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>06</string>\n" +
                "              <string>26</string>\n" +
                "              <string>46</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>06</string>\n" +
                "              <string>26</string>\n" +
                "              <string>46</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>06</string>\n" +
                "              <string>26</string>\n" +
                "              <string>46</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>06</string>\n" +
                "              <string>26</string>\n" +
                "              <string>46</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>06</string>\n" +
                "              <string>26</string>\n" +
                "              <string>46</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>06</string>\n" +
                "              <string>26</string>\n" +
                "              <string>46</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>06</string>\n" +
                "              <string>26</string>\n" +
                "              <string>47</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>07</string>\n" +
                "              <string>27</string>\n" +
                "              <string>48</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>09</string>\n" +
                "              <string>33</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>04</string>\n" +
                "              <string>33</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>03</string>\n" +
                "              <string>33</string>\n" +
                "            </list>\n" +
                "            <list/>\n" +
                "          </hours>\n" +
                "        </timetable>\n" +
                "      </timetable>\n" +
                "      <stop>\n" +
                "        <stop>\n" +
                "          <id>1</id>\n" +
                "          <name>Bulwarowa</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>0</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>2</id>\n" +
                "          <name>Struga</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>1</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>3</id>\n" +
                "          <name>Aleja Róż</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>3</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>4</id>\n" +
                "          <name>Żeromskiego</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>4</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>5</id>\n" +
                "          <name>Teatr Ludowy</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>5</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>6</id>\n" +
                "          <name>Arka</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>7</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>7</id>\n" +
                "          <name>Rondo Hipokratesa</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>9</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>8</id>\n" +
                "          <name>Os.Na Lotnisku</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>11</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>9</id>\n" +
                "          <name>Wiślicka</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>13</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>10</id>\n" +
                "          <name>Bora-Komorowskiego</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>15</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>11</id>\n" +
                "          <name>Miechowity</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>17</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>12</id>\n" +
                "          <name>Rondo Mogilskie</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>22</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>13</id>\n" +
                "          <name>Uniwersytet Ekonomiczny</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>23</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>14</id>\n" +
                "          <name>Politechnika</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>25</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>15</id>\n" +
                "          <name>Nowy Kleparz</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>28</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>16</id>\n" +
                "          <name>Plac Inwalidów</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>30</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>17</id>\n" +
                "          <name>Czarnowiejska</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>32</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>18</id>\n" +
                "          <name>Miasteczko Studenckie AGH</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>35</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>19</id>\n" +
                "          <name>Przybyszewskiego</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>37</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>20</id>\n" +
                "          <name>Zarzecze</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>39</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>21</id>\n" +
                "          <name>Bronowice Wiadukt</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>40</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>22</id>\n" +
                "          <name>Rondo Ofiar Katynia</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>42</delay>\n" +
                "        </stop>\n" +
                "      </stop>\n" +
                "    </course>\n" +
                "    <course>\n" +
                "      <direction>Bulwarowa</direction>\n" +
                "      <timetable>\n" +
                "        <timetable>\n" +
                "          <description>Weekday</description>\n" +
                "          <hours>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list>\n" +
                "              <string>00</string>\n" +
                "              <string>20</string>\n" +
                "              <string>40</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>00</string>\n" +
                "              <string>15</string>\n" +
                "              <string>29</string>\n" +
                "              <string>43</string>\n" +
                "              <string>56</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>10</string>\n" +
                "              <string>26</string>\n" +
                "              <string>41</string>\n" +
                "              <string>55</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>10</string>\n" +
                "              <string>25</string>\n" +
                "              <string>40</string>\n" +
                "              <string>55</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>10</string>\n" +
                "              <string>25</string>\n" +
                "              <string>40</string>\n" +
                "              <string>55</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>10</string>\n" +
                "              <string>25</string>\n" +
                "              <string>40</string>\n" +
                "              <string>55</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>10</string>\n" +
                "              <string>25</string>\n" +
                "              <string>40</string>\n" +
                "              <string>55</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>10</string>\n" +
                "              <string>25</string>\n" +
                "              <string>40</string>\n" +
                "              <string>55</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>10</string>\n" +
                "              <string>25</string>\n" +
                "              <string>40</string>\n" +
                "              <string>54</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>09</string>\n" +
                "              <string>24</string>\n" +
                "              <string>39</string>\n" +
                "              <string>55</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>10</string>\n" +
                "              <string>25</string>\n" +
                "              <string>40</string>\n" +
                "              <string>55</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>10</string>\n" +
                "              <string>25</string>\n" +
                "              <string>40</string>\n" +
                "              <string>55</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>10</string>\n" +
                "              <string>25</string>\n" +
                "              <string>40</string>\n" +
                "              <string>55</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>10</string>\n" +
                "              <string>25</string>\n" +
                "              <string>40</string>\n" +
                "              <string>55</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>11</string>\n" +
                "              <string>25</string>\n" +
                "              <string>40</string>\n" +
                "              <string>55</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>13</string>\n" +
                "              <string>28</string>\n" +
                "              <string>44</string>\n" +
                "              <string>59</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>13</string>\n" +
                "              <string>30</string>\n" +
                "              <string>52</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>12</string>\n" +
                "              <string>35</string>\n" +
                "              <string>55</string>\n" +
                "            </list>\n" +
                "            <list/>\n" +
                "          </hours>\n" +
                "        </timetable>\n" +
                "        <timetable>\n" +
                "          <description>Saturdays</description>\n" +
                "          <hours>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list>\n" +
                "              <string>05</string>\n" +
                "              <string>34</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>03</string>\n" +
                "              <string>33</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>02</string>\n" +
                "              <string>24</string>\n" +
                "              <string>44</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>04</string>\n" +
                "              <string>24</string>\n" +
                "              <string>44</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>04</string>\n" +
                "              <string>24</string>\n" +
                "              <string>44</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>04</string>\n" +
                "              <string>24</string>\n" +
                "              <string>44</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>04</string>\n" +
                "              <string>24</string>\n" +
                "              <string>44</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>04</string>\n" +
                "              <string>24</string>\n" +
                "              <string>44</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>04</string>\n" +
                "              <string>24</string>\n" +
                "              <string>44</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>04</string>\n" +
                "              <string>24</string>\n" +
                "              <string>44</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>04</string>\n" +
                "              <string>24</string>\n" +
                "              <string>44</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>04</string>\n" +
                "              <string>24</string>\n" +
                "              <string>44</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>04</string>\n" +
                "              <string>24</string>\n" +
                "              <string>44</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>04</string>\n" +
                "              <string>24</string>\n" +
                "              <string>44</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>04</string>\n" +
                "              <string>24</string>\n" +
                "              <string>44</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>05</string>\n" +
                "              <string>25</string>\n" +
                "              <string>50</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>15</string>\n" +
                "              <string>37</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>07</string>\n" +
                "              <string>37</string>\n" +
                "            </list>\n" +
                "            <list/>\n" +
                "          </hours>\n" +
                "        </timetable>\n" +
                "        <timetable>\n" +
                "          <description>Holidays</description>\n" +
                "          <hours>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list>\n" +
                "              <string>05</string>\n" +
                "              <string>34</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>03</string>\n" +
                "              <string>33</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>02</string>\n" +
                "              <string>24</string>\n" +
                "              <string>44</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>04</string>\n" +
                "              <string>24</string>\n" +
                "              <string>44</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>04</string>\n" +
                "              <string>24</string>\n" +
                "              <string>44</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>04</string>\n" +
                "              <string>24</string>\n" +
                "              <string>44</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>04</string>\n" +
                "              <string>24</string>\n" +
                "              <string>44</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>04</string>\n" +
                "              <string>24</string>\n" +
                "              <string>44</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>04</string>\n" +
                "              <string>24</string>\n" +
                "              <string>44</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>04</string>\n" +
                "              <string>24</string>\n" +
                "              <string>44</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>04</string>\n" +
                "              <string>24</string>\n" +
                "              <string>44</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>04</string>\n" +
                "              <string>24</string>\n" +
                "              <string>44</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>04</string>\n" +
                "              <string>24</string>\n" +
                "              <string>44</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>04</string>\n" +
                "              <string>24</string>\n" +
                "              <string>44</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>04</string>\n" +
                "              <string>24</string>\n" +
                "              <string>44</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>05</string>\n" +
                "              <string>25</string>\n" +
                "              <string>50</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>15</string>\n" +
                "              <string>37</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>07</string>\n" +
                "              <string>37</string>\n" +
                "            </list>\n" +
                "            <list/>\n" +
                "          </hours>\n" +
                "        </timetable>\n" +
                "      </timetable>\n" +
                "      <stop>\n" +
                "        <stop>\n" +
                "          <id>23</id>\n" +
                "          <name>Chełmońskiego Pętla</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>0</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>24</id>\n" +
                "          <name>Stawowa</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>1</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>25</id>\n" +
                "          <name>Rondo Ofiar Katynia</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>3</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>26</id>\n" +
                "          <name>Bronowice Wiadukt</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>4</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>27</id>\n" +
                "          <name>Zarzecze</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>5</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>28</id>\n" +
                "          <name>Przybyszewskiego</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>8</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>29</id>\n" +
                "          <name>Miasteczko Studenckie AGH</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>10</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>30</id>\n" +
                "          <name>Czarnowiejska</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>12</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>31</id>\n" +
                "          <name>Plac Inwalidów</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>15</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>32</id>\n" +
                "          <name>Nowy Kleparz</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>17</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>33</id>\n" +
                "          <name>Politechnika</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>19</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>34</id>\n" +
                "          <name>Uniwersytet Ekonomiczny</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>21</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>35</id>\n" +
                "          <name>Rondo Mogilskie</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>24</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>36</id>\n" +
                "          <name>Miechowity</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>29</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>37</id>\n" +
                "          <name>Bora-Komorowskiego</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>31</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>38</id>\n" +
                "          <name>Wiślicka</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>34</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>39</id>\n" +
                "          <name>Os.Na Lotnisku</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>36</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>40</id>\n" +
                "          <name>Rondo Hipokratesa</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>39</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>41</id>\n" +
                "          <name>Arka</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>41</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>42</id>\n" +
                "          <name>Teatr Ludowy</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>42</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>43</id>\n" +
                "          <name>Żeromskiego</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>43</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>44</id>\n" +
                "          <name>Aleja Róż</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>44</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>45</id>\n" +
                "          <name>Struga</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>46</delay>\n" +
                "        </stop>\n" +
                "      </stop>\n" +
                "    </course>\n" +
                "  </course>\n" +
                "</line>";
        XmlSerializer serializer = new XmlSerializer();

        ILine line = new CracowLine(501);
        SLineBuilder builder = new SLineBuilder(line);
        SLine sLine = SLineDirector.makeLine(builder);

        String actual = serializer.serializeLine(sLine);
        System.out.println(actual);

        assertThat(expected).isEqualTo(actual);
    }

    @Test
    void is283XmlValid() throws ParsingException, ConnectionError
    {
        String expected = "<line>\n" +
                "  <number>283</number>\n" +
                "  <course>\n" +
                "    <course>\n" +
                "      <direction>Skawina</direction>\n" +
                "      <timetable>\n" +
                "        <timetable>\n" +
                "          <description>Weekday</description>\n" +
                "          <hours>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list>\n" +
                "              <string>15</string>\n" +
                "              <string>39</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>05</string>\n" +
                "              <string>35</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>06</string>\n" +
                "              <string>34</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>03</string>\n" +
                "              <string>34</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>04</string>\n" +
                "              <string>34</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>12</string>\n" +
                "              <string>42</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>22</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>24</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>30</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>04</string>\n" +
                "              <string>22</string>\n" +
                "              <string>38</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>06</string>\n" +
                "              <string>36</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>06</string>\n" +
                "              <string>38</string>\n" +
                "              <string>58</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>38</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>08</string>\n" +
                "              <string>39</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>08</string>\n" +
                "              <string>38</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>08</string>\n" +
                "              <string>35</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>30</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>30</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>30</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>30</string>\n" +
                "            </list>\n" +
                "          </hours>\n" +
                "        </timetable>\n" +
                "        <timetable>\n" +
                "          <description>Saturdays</description>\n" +
                "          <hours>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list>\n" +
                "              <string>55</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>45</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>30</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>15</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>09</string>\n" +
                "              <string>39</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>14</string>\n" +
                "              <string>44</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>18</string>\n" +
                "              <string>54</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>44</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>20</string>\n" +
                "              <string>54</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>28</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>04</string>\n" +
                "              <string>56</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>31</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>11</string>\n" +
                "              <string>54</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>24</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>10</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>00</string>\n" +
                "              <string>40</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>15</string>\n" +
                "              <string>45</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>15</string>\n" +
                "              <string>48</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>15</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>15</string>\n" +
                "            </list>\n" +
                "          </hours>\n" +
                "        </timetable>\n" +
                "        <timetable>\n" +
                "          <description>Holidays</description>\n" +
                "          <hours>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list>\n" +
                "              <string>55</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>55</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>59</string>\n" +
                "            </list>\n" +
                "            <list/>\n" +
                "            <list>\n" +
                "              <string>02</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>03</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>05</string>\n" +
                "              <string>57</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>51</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>51</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>51</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>58</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>58</string>\n" +
                "            </list>\n" +
                "            <list/>\n" +
                "            <list>\n" +
                "              <string>01</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>02</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>02</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>07</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>05</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>02</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>05</string>\n" +
                "            </list>\n" +
                "          </hours>\n" +
                "        </timetable>\n" +
                "      </timetable>\n" +
                "      <stop>\n" +
                "        <stop>\n" +
                "          <id>1</id>\n" +
                "          <name>Czerwone Maki P+R</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>0</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>2</id>\n" +
                "          <name>Czerwone Maki P+R</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>1</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>3</id>\n" +
                "          <name>Bunscha</name>\n" +
                "          <onDemand>true</onDemand>\n" +
                "          <delay>2</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>4</id>\n" +
                "          <name>Babińskiego</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>3</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>5</id>\n" +
                "          <name>Skotniki</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>4</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>6</id>\n" +
                "          <name>Baczyńskiego</name>\n" +
                "          <onDemand>true</onDemand>\n" +
                "          <delay>5</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>7</id>\n" +
                "          <name>Wrony</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>7</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>8</id>\n" +
                "          <name>Skawina Podlipki</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>9</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>9</id>\n" +
                "          <name>Skawina Rzepnik</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>10</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>10</id>\n" +
                "          <name>Skawina Cmentarz</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>12</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>11</id>\n" +
                "          <name>Skawina Popiełuszki</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>13</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>12</id>\n" +
                "          <name>Skawina Ajka</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>14</delay>\n" +
                "        </stop>\n" +
                "      </stop>\n" +
                "    </course>\n" +
                "    <course>\n" +
                "      <direction>Czerwone Maki P+R</direction>\n" +
                "      <timetable>\n" +
                "        <timetable>\n" +
                "          <description>Weekday</description>\n" +
                "          <hours>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list>\n" +
                "              <string>35</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>00</string>\n" +
                "              <string>30</string>\n" +
                "              <string>57</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>30</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>00</string>\n" +
                "              <string>30</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>00</string>\n" +
                "              <string>30</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>00</string>\n" +
                "              <string>20</string>\n" +
                "              <string>50</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>50</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>50</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>30</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>00</string>\n" +
                "              <string>30</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>00</string>\n" +
                "              <string>30</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>00</string>\n" +
                "              <string>30</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>00</string>\n" +
                "              <string>20</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>00</string>\n" +
                "              <string>30</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>00</string>\n" +
                "              <string>30</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>00</string>\n" +
                "              <string>30</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>00</string>\n" +
                "              <string>50</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>50</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>50</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>20</string>\n" +
                "              <string>50</string>\n" +
                "            </list>\n" +
                "          </hours>\n" +
                "        </timetable>\n" +
                "        <timetable>\n" +
                "          <description>Saturdays</description>\n" +
                "          <hours>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list>\n" +
                "              <string>15</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>05</string>\n" +
                "              <string>50</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>36</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>31</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>00</string>\n" +
                "              <string>35</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>08</string>\n" +
                "              <string>50</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>30</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>10</string>\n" +
                "              <string>41</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>18</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>10</string>\n" +
                "              <string>47</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>25</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>12</string>\n" +
                "              <string>38</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>25</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>12</string>\n" +
                "              <string>40</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>25</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>10</string>\n" +
                "              <string>40</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>15</string>\n" +
                "              <string>39</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>15</string>\n" +
                "              <string>35</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>35</string>\n" +
                "            </list>\n" +
                "          </hours>\n" +
                "        </timetable>\n" +
                "        <timetable>\n" +
                "          <description>Holidays</description>\n" +
                "          <hours>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list/>\n" +
                "            <list>\n" +
                "              <string>15</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>15</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>20</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>28</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>25</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>30</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>18</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>13</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>13</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>13</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>20</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>20</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>24</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>22</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>22</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>27</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>25</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>23</string>\n" +
                "            </list>\n" +
                "            <list>\n" +
                "              <string>25</string>\n" +
                "            </list>\n" +
                "          </hours>\n" +
                "        </timetable>\n" +
                "      </timetable>\n" +
                "      <stop>\n" +
                "        <stop>\n" +
                "          <id>13</id>\n" +
                "          <name>Skawina</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>0</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>14</id>\n" +
                "          <name>Skawina Ajka</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>1</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>15</id>\n" +
                "          <name>Skawina Cmentarz</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>3</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>16</id>\n" +
                "          <name>Skawina Rzepnik</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>5</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>17</id>\n" +
                "          <name>Skawina Podlipki</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>6</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>18</id>\n" +
                "          <name>Wrony</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>8</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>19</id>\n" +
                "          <name>Baczyńskiego</name>\n" +
                "          <onDemand>true</onDemand>\n" +
                "          <delay>10</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>20</id>\n" +
                "          <name>Skotniki</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>12</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>21</id>\n" +
                "          <name>Babińskiego</name>\n" +
                "          <onDemand>false</onDemand>\n" +
                "          <delay>13</delay>\n" +
                "        </stop>\n" +
                "        <stop>\n" +
                "          <id>22</id>\n" +
                "          <name>Bunscha</name>\n" +
                "          <onDemand>true</onDemand>\n" +
                "          <delay>14</delay>\n" +
                "        </stop>\n" +
                "      </stop>\n" +
                "    </course>\n" +
                "  </course>\n" +
                "</line>";
        XmlSerializer serializer = new XmlSerializer();

        ILine line = new CracowLine(283);
        SLineBuilder builder = new SLineBuilder(line);
        SLine sLine = SLineDirector.makeLine(builder);

        String actual = serializer.serializeLine(sLine);

        System.out.println(actual);

        assertThat(expected).isEqualTo(actual);
    }
}
